name: coco_explorer
description: Common Objects in Context (COCO) is an image and captions dataset used for training and evaluating machine learning models. COCO Explorer is a mobile app that allows a user to search the dataset by category and view the results.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  auto_route: ^5.0.1
  flutter_bloc: ^8.1.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  logger: ^1.1.0
  json_annotation: ^4.6.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  dartz: ^0.10.1
  internet_connection_checker: ^0.0.1+4
  equatable: ^2.0.5
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.2
  retrofit_generator: ^4.0.3+1
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.4
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
